spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:file:./h2db/sample
      driver-class-name: org.h2.Driver
      username: sa
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jwt:
    issuer: test@test.com
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

